services:
  dicom_router:
    image: dicom-router:0.0.1
    container_name: dicom_router
    restart: always
    environment:
      - POSTGRES_DB=dicom_router
      - POSTGRES_USER=dicom_user
      - POSTGRES_PASSWORD=dicom_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./media:/app/media
    depends_on:
      - postgres
  postgres:
    image: postgres:17.6-alpine
    container_name: dicom_router_db
    environment:
      POSTGRES_DB: dicom_router
      POSTGRES_USER: dicom_user
      POSTGRES_PASSWORD: dicom_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:1.29.1-alpine
    container_name: dicom_router_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dicom_router