# Generated by Django 5.2.6 on 2025-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_title', models.CharField(help_text='AE Title of the DICOM client', max_length=64)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the DICOM client')),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this authorization is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DICOM Authorization',
                'verbose_name_plural': 'DICOM Authorizations',
                'unique_together': {('ae_title', 'ip_address')},
            },
        ),
    ]
